#!/usr/bin/env bash
#
# Summary: Run an executable with the selected Terraform version
#
# Usage: pckenv exec <command> [arg1 arg2...]
#
# Runs an executable by first preparing PATH so that the selected Terraform
# version's `bin' directory is at the front.
#
# For example, if the currently selected Terraform version is 0.7.0:
#   pckenv exec plan
#
# is equivalent to:
#   PATH="$PCKENV_ROOT/versions/0.7.0/bin:$PATH" terraform plan

set -uo pipefail;

####################################
# Ensure we can execute standalone #
####################################

function early_death() {
  echo "[FATAL] ${0}: ${1}" >&2;
  exit 1;
};

if [ -z "${PCKENV_ROOT:-""}" ]; then
  # http://stackoverflow.com/questions/1055671/how-can-i-get-the-behavior-of-gnus-readlink-f-on-a-mac
  readlink_f() {
    local target_file="${1}";
    local file_name;

    while [ "${target_file}" != "" ]; do
      cd "$(dirname ${target_file})" || early_death "Failed to 'cd \$(dirname ${target_file})' while trying to determine PCKENV_ROOT";
      file_name="$(basename "${target_file}")" || early_death "Failed to 'basename \"${target_file}\"' while trying to determine PCKENV_ROOT";
      target_file="$(readlink "${file_name}")";
    done;

    echo "$(pwd -P)/${file_name}";
  };

  PCKENV_ROOT="$(cd "$(dirname "$(readlink_f "${0}")")/.." && pwd)";
  [ -n "${PCKENV_ROOT}" ] || early_death "Failed to 'cd \"\$(dirname \"\$(readlink_f \"${0}\")\")/..\" && pwd' while trying to determine PCKENV_ROOT";
else
  PCKENV_ROOT="${PCKENV_ROOT%/}";
fi;
export PCKENV_ROOT;

if [ -n "${PCKENV_HELPERS:-""}" ]; then
  log 'debug' 'PCKENV_HELPERS is set, not sourcing helpers again';
else
  [ "${PCKENV_DEBUG:-0}" -gt 0 ] && echo "[DEBUG] Sourcing helpers from ${PCKENV_ROOT}/lib/helpers.sh";
  if source "${PCKENV_ROOT}/lib/helpers.sh"; then
    log 'debug' 'Helpers sourced successfully';
  else
    early_death "Failed to source helpers from ${PCKENV_ROOT}/lib/helpers.sh";
  fi;
fi;

# Ensure libexec and bin are in $PATH
for dir in libexec bin; do
  case ":${PATH}:" in
    *:${PCKENV_ROOT}/${dir}:*) log 'debug' "\$PATH already contains '${PCKENV_ROOT}/${dir}', not adding it again";;
    *)
      log 'debug' "\$PATH does not contain '${PCKENV_ROOT}/${dir}', prepending and exporting it now";
      export PATH="${PCKENV_ROOT}/${dir}:${PATH}";
      ;;
  esac;
done;

#####################
# Begin Script Body #
#####################

pckenv-exec "$@";
