#!/usr/bin/env bash

set -uo pipefail;

####################################
# Ensure we can execute standalone #
####################################

function early_death() {
  echo "[FATAL] ${0}: ${1}" >&2;
  exit 1;
};

if [ -z "${PCKENV_ROOT:-""}" ]; then
  # http://stackoverflow.com/questions/1055671/how-can-i-get-the-behavior-of-gnus-readlink-f-on-a-mac
  readlink_f() {
    local target_file="${1}";
    local file_name;

    while [ "${target_file}" != "" ]; do
      cd "$(dirname "${target_file}")" || early_death "Failed to 'cd \$(dirname ${target_file})' while trying to determine PCKENV_ROOT";
      file_name="$(basename "${target_file}")" || early_death "Failed to 'basename \"${target_file}\"' while trying to determine PCKENV_ROOT";
      target_file="$(readlink "${file_name}")";
    done;

    echo "$(pwd -P)/${file_name}";
  };

  PCKENV_ROOT="$(cd "$(dirname "$(readlink_f "${0}")")/.." && pwd)";
  [ -n "${PCKENV_ROOT}" ] || early_death "Failed to 'cd \"\$(dirname \"\$(readlink_f \"${0}\")\")/..\" && pwd' while trying to determine PCKENV_ROOT";
else
  PCKENV_ROOT="${PCKENV_ROOT%/}";
fi;
export PCKENV_ROOT;

if [ -n "${PCKENV_HELPERS:-""}" ]; then
  log 'debug' 'PCKENV_HELPERS is set, not sourcing helpers again';
else
  [ "${PCKENV_DEBUG:-0}" -gt 0 ] && echo "[DEBUG] Sourcing helpers from ${PCKENV_ROOT}/lib/helpers.sh";
  if source "${PCKENV_ROOT}/lib/helpers.sh"; then
    log 'debug' 'Helpers sourced successfully';
  else
    early_death "Failed to source helpers from ${PCKENV_ROOT}/lib/helpers.sh";
  fi;
fi;

# Ensure libexec and bin are in $PATH
for dir in libexec bin; do
  case ":${PATH}:" in
    *:${PCKENV_ROOT}/${dir}:*) log 'debug' "\$PATH already contains '${PCKENV_ROOT}/${dir}', not adding it again";;
    *)
      log 'debug' "\$PATH does not contain '${PCKENV_ROOT}/${dir}', prepending and exporting it now";
      export PATH="${PCKENV_ROOT}/${dir}:${PATH}";
      ;;
  esac;
done;

#####################
# Begin Script Body #
#####################

if [ "${#}" -ne 0 ];then
  echo "usage: pckenv list-remote" 1>&2;
  exit 1;
fi;

PCKENV_REMOTE="${PCKENV_REMOTE:-https://releases.hashicorp.com}";
log 'debug' "PCKENV_REMOTE: ${PCKENV_REMOTE}";

declare remote_versions;
remote_versions="$(curlw -sSf "${PCKENV_REMOTE}/packer/")" \
  || log 'error' "Failed to download remote versions from ${PCKENV_REMOTE}/packer/";

#log 'debug' "Remote versions available: ${remote_versions}"; # Even in debug mode this is too verbose

if [[ "${PCKENV_REVERSE_REMOTE:-0}" -eq 1 ]]; then
  grep -o -E "[0-9]+\.[0-9]+\.[0-9]+(-(rc|beta|alpha|oci)-?[0-9]*)?" <<<"${remote_versions}" | uniq | awk '{a[i++]=$0} END {for (j=i-1; j>=0;) print a[j--] }';
else
  grep -o -E "[0-9]+\.[0-9]+\.[0-9]+(-(rc|beta|alpha|oci)-?[0-9]*)?" <<<"${remote_versions}" | uniq;
fi;
